"""add click logs and update users

Revision ID: 05fdee430458
Revises: e0ec1cdd321d
Create Date: 2026-03-23 03:57:07.681168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05fdee430458'
down_revision: Union[str, Sequence[str], None] = 'e0ec1cdd321d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('click_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('subunionid', sa.String(length=64), nullable=False),
    sa.Column('promotion_url', sa.String(length=1000), nullable=True),
    sa.Column('click_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_click_logs_id'), 'click_logs', ['id'], unique=False)
    op.create_index(op.f('ix_click_logs_product_id'), 'click_logs', ['product_id'], unique=False)
    op.create_index(op.f('ix_click_logs_subunionid'), 'click_logs', ['subunionid'], unique=False)
    op.create_index(op.f('ix_click_logs_user_id'), 'click_logs', ['user_id'], unique=False)
    op.add_column('users', sa.Column('wechat_unionid', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'users', ['wechat_unionid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'wechat_unionid')
    op.drop_index(op.f('ix_click_logs_user_id'), table_name='click_logs')
    op.drop_index(op.f('ix_click_logs_subunionid'), table_name='click_logs')
    op.drop_index(op.f('ix_click_logs_product_id'), table_name='click_logs')
    op.drop_index(op.f('ix_click_logs_id'), table_name='click_logs')
    op.drop_table('click_logs')
    # ### end Alembic commands ###
