"""add orders and cashback records

Revision ID: 2cd6327fdc61
Revises: 05fdee430458
Create Date: 2026-03-23 04:21:12.407944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cd6327fdc61'
down_revision: Union[str, Sequence[str], None] = '05fdee430458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jd_order_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('subunionid', sa.String(length=64), nullable=True),
    sa.Column('site_id', sa.String(length=64), nullable=True),
    sa.Column('position_id', sa.String(length=64), nullable=True),
    sa.Column('sku_id', sa.String(length=64), nullable=True),
    sa.Column('sku_name', sa.String(length=255), nullable=True),
    sa.Column('order_amount', sa.Float(), nullable=True),
    sa.Column('actual_cos_price', sa.Float(), nullable=True),
    sa.Column('estimate_cos_price', sa.Float(), nullable=True),
    sa.Column('order_status', sa.String(length=50), nullable=True),
    sa.Column('order_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finish_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_jd_order_id'), 'orders', ['jd_order_id'], unique=True)
    op.create_index(op.f('ix_orders_position_id'), 'orders', ['position_id'], unique=False)
    op.create_index(op.f('ix_orders_product_id'), 'orders', ['product_id'], unique=False)
    op.create_index(op.f('ix_orders_site_id'), 'orders', ['site_id'], unique=False)
    op.create_index(op.f('ix_orders_sku_id'), 'orders', ['sku_id'], unique=False)
    op.create_index(op.f('ix_orders_subunionid'), 'orders', ['subunionid'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('cashback_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('expected_cashback_amount', sa.Float(), nullable=True),
    sa.Column('actual_cashback_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cashback_records_id'), 'cashback_records', ['id'], unique=False)
    op.create_index(op.f('ix_cashback_records_order_id'), 'cashback_records', ['order_id'], unique=False)
    op.create_index(op.f('ix_cashback_records_user_id'), 'cashback_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cashback_records_user_id'), table_name='cashback_records')
    op.drop_index(op.f('ix_cashback_records_order_id'), table_name='cashback_records')
    op.drop_index(op.f('ix_cashback_records_id'), table_name='cashback_records')
    op.drop_table('cashback_records')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_subunionid'), table_name='orders')
    op.drop_index(op.f('ix_orders_sku_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_site_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_product_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_position_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_jd_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
