"""change money fields to numeric

Revision ID: aef275172fa1
Revises: 2cd6327fdc61
Create Date: 2026-03-23 04:52:41.822762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aef275172fa1'
down_revision: Union[str, Sequence[str], None] = '2cd6327fdc61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cashback_records', 'expected_cashback_amount',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('cashback_records', 'actual_cashback_amount',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('orders', 'order_amount',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('orders', 'actual_cos_price',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('orders', 'estimate_cos_price',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('products', 'price',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('products', 'coupon_price',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('products', 'estimated_commission',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'estimated_commission',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('products', 'coupon_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('products', 'price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('orders', 'estimate_cos_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('orders', 'actual_cos_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('orders', 'order_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('cashback_records', 'actual_cashback_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('cashback_records', 'expected_cashback_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    # ### end Alembic commands ###
